### ISSUE TITLE
Bug in escape string processing

### ISSUE THREAD

**Issue by onexdata** [hex13/atom-lupa#35]
This line:

> log('\033');

will break parsing.

**Comment by hex13** [comment]
is this even allowed in JS? ESLint gives me error:
![image](https://cloud.githubusercontent.com/assets/3883359/19293460/c7ca7c36-9024-11e6-84ee-d450d3d1d251.png).

Judging from this message there is a difference if strict mode is enabled or not:
Chrome Dev Tools: console
`(function () { return '\033' })()` 
(runs without errors);

`(function () {"use strict"; return '\033'})()` 
use strict enabled - there is an error:
`Uncaught SyntaxError: Octal literals are not allowed in strict mode.`

![image](https://cloud.githubusercontent.com/assets/3883359/19293502/3f3a6bc8-9025-11e6-86c5-3eff2d94d326.png)

So I think there are two possible things to do:
- Because strict mode is recommended anyway (and "use strict" may be automatically added on when using bundlers) you could rewrite your code to comply with use strict (it seems to be very easy in this case - just use hexadecimal instead of octals).
- Although I would like my plugin to work with many codebases (and people write code in many different ways) I could check options I pass to parser and think about either automatically detecting (use strict enabled/disabled) or  by making checkbox in settings.
